import { expect, test, type Page } from '@playwright/test'

const projectPath = '/farm-stand/'

async function openShop(page: Page, showAll = true) {
  await page.goto(`${projectPath}#shop`, { waitUntil: 'networkidle' })
  await expect(page.getByRole('heading', { name: 'Shop the stand.' })).toBeVisible()
  if (showAll) await page.getByRole('button', { name: /^All 48/ }).click()
}

async function addProduct(page: Page, productId: string, name = 'Add to basket') {
  const count = page.locator('.basket-button span')
  const before = Number(await count.textContent())
  await page.locator(`#product-${productId}`).getByRole('button', { name }).click()
  await expect(count).toHaveText(String(before + 1))
}

test('project-path build loads the opening and keeps entrance links usable', async ({ page }) => {
  const failedResponses: string[] = []
  page.on('response', (response) => { if (response.status() >= 400) failedResponses.push(`${response.status()} ${response.url()}`) })
  await page.goto(projectPath, { waitUntil: 'networkidle' })
  await expect(page.locator('.hero-stage')).toHaveClass(/hero-stage--ready/)
  await expect(page.getByRole('heading', { name: 'This is what your farm could look like online.' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: /straight to/i }).getByRole('link')).toHaveCount(4)
  await expect(page.getByRole('link', { name: 'Shop' }).last()).toHaveAttribute('href', '#shop')
  const resources = await page.evaluate(() => performance.getEntriesByType('resource').map((entry) => new URL(entry.name).pathname))
  expect(resources.every((path) => path.startsWith('/farm-stand/'))).toBe(true)
  expect(failedResponses).toEqual([])
})

test('opening starts on meaningful downward intent, pauses, resumes, skips, and stays complete', async ({ page }) => {
  await page.goto(projectPath)
  const stage = page.locator('.hero-stage')
  await expect(stage).toHaveAttribute('data-opening-state', 'waiting')
  await page.mouse.wheel(0, 4)
  await expect(stage).toHaveAttribute('data-opening-state', 'waiting')
  await page.getByRole('button', { name: 'Open the stand' }).click()
  await expect(stage).toHaveAttribute('data-opening-state', 'playing')
  await expect.poll(async () => Number(await stage.getAttribute('data-requested-progress'))).toBeGreaterThan(.01)
  await page.getByRole('button', { name: 'Pause opening' }).click()
  await expect(stage).toHaveAttribute('data-opening-state', 'paused')
  const paused = Number(await stage.getAttribute('data-requested-progress'))
  await page.mouse.wheel(0, -200)
  await page.waitForTimeout(250)
  expect(Number(await stage.getAttribute('data-requested-progress'))).toBeCloseTo(paused, 2)
  await page.getByRole('button', { name: 'Resume opening' }).click()
  await expect(stage).toHaveAttribute('data-opening-state', 'playing')
  await page.getByRole('button', { name: 'Skip opening' }).click()
  await expect(stage).toHaveAttribute('data-opening-state', 'open')
  await expect(stage).toHaveAttribute('data-requested-progress', '1.0000')
  await page.reload()
  await expect(stage).toHaveAttribute('data-opening-state', 'open')
  await expect(page.getByRole('button', { name: 'Open the stand' })).toHaveCount(0)
})

test('keyboard intent starts the clock and leaving the hero settles it open', async ({ page }) => {
  await page.goto(projectPath)
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'playing')
  await page.locator('#shop').scrollIntoViewIfNeeded()
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'open')
  await expect(page.getByRole('heading', { name: 'Shop the stand.' })).toBeVisible()
})

test('touch intent starts the opening without scroll ownership', async ({ page }) => {
  await page.goto(projectPath)
  await page.locator('.hero-stage').evaluate((stage) => {
    const start = new Touch({ identifier: 1, target: stage, clientX: 100, clientY: 500 })
    const move = new Touch({ identifier: 1, target: stage, clientX: 100, clientY: 470 })
    stage.dispatchEvent(new TouchEvent('touchstart', { bubbles: true, touches: [start] }))
    stage.dispatchEvent(new TouchEvent('touchmove', { bubbles: true, touches: [move] }))
  })
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'playing')
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
})

test('hidden-tab lifecycle time is excluded from the opening clock', async ({ page }) => {
  await page.goto(projectPath)
  await page.getByRole('button', { name: 'Open the stand' }).click()
  await page.waitForTimeout(350)
  const before = Number(await page.locator('.hero-stage').getAttribute('data-requested-progress'))
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, value: true })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await page.waitForTimeout(700)
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, value: false })
    document.dispatchEvent(new Event('visibilitychange'))
  })
  await page.waitForTimeout(80)
  const after = Number(await page.locator('.hero-stage').getAttribute('data-requested-progress'))
  expect(after - before).toBeLessThan(.12)
})

test('direct destination bypasses the opening and reveals non-featured products', async ({ page }) => {
  await page.goto(`${projectPath}#product-eggs`, { waitUntil: 'networkidle' })
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'open')
  await expect(page.locator('#product-eggs')).toBeVisible()
  await expect(page.locator('#product-eggs')).toBeFocused()
})

test('market exposes exact counts, curated default, subgroup browse, search, and reset', async ({ page }) => {
  await openShop(page, false)
  await expect(page.locator('.product-card')).toHaveCount(12)
  await expect(page.getByRole('button', { name: /^Fruit & veg 28/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Butcher 6/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Eggs & dairy 4/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Pantry 4/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Boxes 2/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Farm goods 4/ })).toBeVisible()
  await page.getByRole('button', { name: /^Fruit & veg 28/ }).click()
  await expect(page.locator('.product-card')).toHaveCount(28)
  await page.getByRole('button', { name: 'Fruit 16' }).click()
  await expect(page.locator('.product-card')).toHaveCount(16)
  await page.getByLabel('Search the market').fill('currants')
  await expect(page.locator('.product-card')).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'Red currants' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear and show market picks' }).click()
  await expect(page.locator('.product-card')).toHaveCount(12)
})

test('basket supports variants, quantity, undo, preview, and clear', async ({ page }) => {
  await openShop(page)
  await addProduct(page, 'apple')
  const shirt = page.locator('#product-farm-tee')
  await shirt.getByLabel('Size').selectOption('s')
  await addProduct(page, 'farm-tee')
  await shirt.getByLabel('Size').selectOption('m')
  await addProduct(page, 'farm-tee')
  await expect(page.locator('#product-squash').getByRole('button', { name: 'Unavailable example' })).toBeDisabled()
  await page.getByRole('button', { name: /Open demonstration basket, 3 items/ }).click()
  const drawer = page.getByRole('dialog', { name: /Your basket/ })
  await expect(drawer.getByText('Size: Small')).toBeVisible()
  await expect(drawer.getByText('Size: Medium')).toBeVisible()
  await drawer.getByRole('button', { name: 'Increase Orchard apples quantity' }).click()
  await expect(drawer.getByLabel('Quantity for Orchard apples')).toContainText('2')
  await drawer.locator('.basket-lines li').filter({ hasText: 'Size: Small' }).getByRole('button', { name: 'Remove' }).click()
  await drawer.getByRole('button', { name: 'Undo' }).click()
  await expect(drawer.getByText('Size: Small')).toBeVisible()
  await drawer.getByRole('button', { name: 'Preview collection' }).click()
  await expect(drawer).toContainText('never removes, substitutes, or reprices')
  await drawer.getByRole('button', { name: 'Save this preview' }).click()
  await expect(drawer).toContainText('Nothing was sent')
  await drawer.getByRole('button', { name: 'Clear demonstration basket' }).click()
  await drawer.getByRole('button', { name: 'Yes, clear it' }).click()
  await expect(drawer).toContainText('Your demonstration basket is empty.')
})

test('legacy basket migrates deliberately and ignores stored prices', async ({ page }) => {
  await openShop(page)
  await page.evaluate(() => {
    sessionStorage.removeItem('farm-stand-demo-basket-v2')
    sessionStorage.setItem('farm-stand-demo-basket-v1', JSON.stringify({ apple: 2, eggs: 1, unknown: 4, squash: 1, price: 1 }))
  })
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByRole('button', { name: /Open demonstration basket, 3 items/ }).click()
  const drawer = page.getByRole('dialog', { name: /Your basket/ })
  await expect(drawer.locator('.basket-total')).toContainText('$20.00')
  const storage = await page.evaluate(() => ({ next: sessionStorage.getItem('farm-stand-demo-basket-v2'), legacy: sessionStorage.getItem('farm-stand-demo-basket-v1') }))
  expect(storage.next).toContain('"version":2')
  expect(storage.legacy).toBeNull()
})

test('farm-life scenes use matching posters and never play more than one large video', async ({ page }) => {
  await page.goto(`${projectPath}#hens`, { waitUntil: 'networkidle' })
  await expect(page.locator('#hens video')).toHaveAttribute('poster', /hens-poster\.avif/)
  await expect(page.locator('#cattle video')).toHaveAttribute('poster', /cattle-poster\.avif/)
  await expect(page.locator('#sheep video')).toHaveAttribute('poster', /sheep-poster\.avif/)
  expect(await page.locator('.farm-profile video').evaluateAll((videos) => videos.filter((video) => !(video as HTMLVideoElement).paused).length)).toBeLessThanOrEqual(1)
  await page.locator('#cattle').scrollIntoViewIfNeeded()
  await page.waitForTimeout(300)
  expect(await page.locator('.farm-profile video').evaluateAll((videos) => videos.filter((video) => !(video as HTMLVideoElement).paused).length)).toBeLessThanOrEqual(1)
  await page.locator('#hens').getByRole('link', { name: 'View eggs' }).click()
  await expect(page).toHaveURL(/#product-eggs$/)
  await expect(page.locator('#product-eggs')).toBeFocused()
})

test('reduced motion presents complete still states and keeps manual video control', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto(projectPath)
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'open')
  await expect(page.getByTestId('scene-host')).toBeHidden()
  await expect(page.locator('.market-opening__plate')).toBeVisible()
  await page.goto(`${projectPath}#sheep`)
  await expect(page.locator('#sheep').getByRole('button', { name: 'Play scene' })).toBeVisible()
  expect(await page.locator('#sheep video').evaluate((video) => (video as HTMLVideoElement).paused)).toBe(true)
})

test('model, opening-image, product-image, and video failures retain complete fallbacks', async ({ page }) => {
  await page.route('**/models/**', (route) => route.abort())
  await page.route('**/media/market-opening-open-*.avif', (route) => route.abort())
  await page.route('**/media/catalogue-expanded/apple.avif', (route) => route.abort())
  await page.route('**/media/farm-life-motion/hens.mp4', (route) => route.abort())
  await page.goto(projectPath)
  await expect(page.locator('.hero-stage')).toHaveClass(/hero-stage--fallback/)
  await expect(page.locator('.hero-stage')).toHaveAttribute('data-opening-state', 'fallback')
  await openShop(page, false)
  await expect(page.getByRole('img', { name: /Orchard apples image unavailable/ })).toBeVisible()
  await page.goto(`${projectPath}#hens`)
  await expect(page.getByRole('img', { name: /Hens video unavailable/ })).toBeVisible()
})

test('layouts avoid horizontal overflow and portrait basket stays within the viewport', async ({ page }) => {
  for (const size of [{ width: 320, height: 740 }, { width: 900, height: 700 }, { width: 960, height: 540 }]) {
    await page.setViewportSize(size)
    await openShop(page)
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth), `${size.width}x${size.height}`).toBeLessThanOrEqual(1)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await addProduct(page, 'apple')
  await page.getByRole('button', { name: /Open demonstration basket/ }).click()
  await page.waitForTimeout(450)
  const rect = await page.getByRole('dialog', { name: /Your basket/ }).evaluate((node) => node.getBoundingClientRect())
  expect(rect.left).toBeGreaterThanOrEqual(0)
  expect(rect.right).toBeLessThanOrEqual(390)
  expect(rect.bottom).toBeLessThanOrEqual(844)
})

test('visit, service, and contact remain fictional and send nothing', async ({ page }) => {
  const writes: string[] = []
  page.on('request', (request) => { if (request.method() !== 'GET') writes.push(`${request.method()} ${request.url()}`) })
  await page.goto(`${projectPath}#visit`)
  await expect(page.getByText('Illustrative periods, not a live schedule.')).toBeVisible()
  await expect(page.getByText('No address or geographic directions are configured.')).toBeVisible()
  await page.locator('#website').scrollIntoViewIfNeeded()
  await page.getByLabel('Opens').fill('10:30')
  await expect(page.locator('.try-update__preview')).toContainText('10:30 am–1:00 pm')
  await page.locator('#contact').scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: /send|submit/i })).toHaveCount(0)
  expect(writes).toEqual([])
})

test('two-hundred-percent text sizing keeps the market operable without horizontal scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await openShop(page, false)
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await expect(page.getByRole('button', { name: /^Boxes 2/ })).toBeVisible()
})
