const publicAsset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`

export type FarmLifeId = 'hens' | 'cattle' | 'sheep'

export const farmLifeProfiles = [
  {
    id: 'hens' as const,
    variant: 'ground' as const,
    label: 'Hens',
    heading: 'Hens',
    note: 'Mind the little ones.',
    description: 'A hen and her chicks, busy at ground level.',
    video: publicAsset('media/farm-life-motion/hens.mp4'),
    poster: publicAsset('media/farm-life-motion/hens-poster.avif'),
    alt: 'A hen and a group of chicks moving through grass beside a stone wall',
    link: '#product-eggs',
    linkLabel: 'View eggs',
    soundLabel: 'Hear a cluck',
    creator: 'Anurag Gusain',
    sourceUrl: 'https://www.pexels.com/video/29229103/',
  },
  {
    id: 'cattle' as const,
    variant: 'wide' as const,
    label: 'Cattle',
    heading: 'Cattle',
    note: 'In no particular hurry.',
    description: 'A herd grazing in open pasture.',
    video: publicAsset('media/farm-life-motion/cattle.mp4'),
    poster: publicAsset('media/farm-life-motion/cattle-poster.avif'),
    alt: 'A cattle herd spread across a wide pasture beneath distant mountains',
    link: '#visit',
    linkLabel: 'Visiting information',
    soundLabel: 'Hear the cattle',
    creator: 'Taryn Elliott',
    sourceUrl: 'https://www.pexels.com/video/herd-of-cows-in-a-pastureland-3769204/',
  },
  {
    id: 'sheep' as const,
    variant: 'reveal' as const,
    label: 'Sheep',
    heading: 'Sheep',
    note: 'Keeping close.',
    description: 'A flock moving through the grass.',
    video: publicAsset('media/farm-life-motion/sheep.mp4'),
    poster: publicAsset('media/farm-life-motion/sheep-poster.avif'),
    alt: 'A flock of sheep moving through grass and low shrubs beneath a tree',
    link: '#shop',
    linkLabel: 'Back to the market',
    soundLabel: 'Hear a bleat',
    creator: 'Matthias Groeneveld',
    sourceUrl: 'https://www.pexels.com/video/12116085/',
  },
] as const
